# Site
title:        "Kimai Time-Tracking"
locale:       "en_US"
lang:         "en_US"
baseurl:      ""
url:          "https://www.kimai.org"
bing-id:      "874E17F27A8EABE9DDAED762FC498BC4"

kimai_v2_version: "1.30.3"
kimai_v2_website: https://github.com/kimai/www.kimai.org
kimai_v2_repo: https://github.com/kimai/kimai
kimai_v2_forum: https://github.com/kimai/kimai/discussions
kimai_v2_file: https://github.com/kimai/kimai/blob/main
kimai_v2_demo: https://demo.kimai.org
kimai_v1_repo: https://github.com/kimai/kimai1

languages:
    - de
    - en
    - fr
    - hr

date_format:
    ar: "%Y-%m-%d"
    de: "%d.%m.%Y"
    en: "%Y-%m-%d"
    fa: "%Y-%m-%d"
    fr: "%d.%m.%Y"
    he: "%Y-%m-%d"
    hr: "%-d. %-m. %Y."
    ko: "%Y-%m-%d"
    nb_NO: "%Y-%m-%d"
    pt_BR: "%Y-%m-%d"
    ru: "%Y-%m-%d"
    uk: "%Y-%m-%d"
    vi: "%Y-%m-%d"
    zh_Hans: "%Y-%m-%d"

language_names:
    ar: العربية
    de: Deutsch
    en: English
    fa: فارسی
    fr: Français
    he: עברית
    hr: Hrvatski
    ko: 한국어
    nb_NO: Norwegian Bokmål (Norway)
    pt_BR: Português (Brasil)
    ru: русский
    uk: українська
    vi: Tiếng Việt
    zh_Hans: 中文（繁體）

collections:
  documentation:
    output: true
    permalink: "/:collection/:name.html"
  docu_versioned:
    output: true
    permalink: "/documentation/:path.html"
  pages:
    output: true
    permalink: "/:name/"
  error:
    output: true
    permalink: "/:name.html"
  store:
    output: true
    permalink: "/store/:title.html"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/blog/:year/:title/"
      layout: post
      author: kevinpapst
      lang: en
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      lang: en
  - scope:
      path: ""
      type: error
    values:
      layout: error
      sitemap: false
      lang: en
  - scope:
      path: ""
      type: documentation
    values:
      layout: documentation
      lang: en
  - scope:
      path: ""
      type: docu_versioned
    values:
      layout: docu-versioned
      lang: en
  - scope:
      path: ""
      type: store
    values:
      layout: store-item
      lang: en

markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

# see Gemfile
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

jekyll-mentions:
    base_url: https://github.com

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
  - old
  - .gitignore
  - .git
  - .idea
  - _includes
  - .DS_Store
  - assets/*.scss
  - assets/bundle.js
  - translate-pages.php
  - .github

whitelist:
    - jekyll-redirect-from

################### REMOVE ME ###################
base_color: '#467fcf'

author:
    name: Kevin Papst
    url: https://www.kevinpapst.de

# Kimai exclusive
use_pagination: false
name: Kimai Time-Tracking

bio: "Kimai Time-Tracking"
description:  "Kimai time-tracking app - a free and open-source PHP based time-tracker for agencies and freelancer"
